# Generated by Django 4.1.7 on 2023-04-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmusercode',
            name='code',
            field=models.IntegerField(),
        ),
    ]
